# Generated by Django 4.1.7 on 2023-02-18 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaf_types',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Leaf',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=31)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.leaf_types')),
            ],
        ),
        migrations.CreateModel(
            name='Key_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.leaf')),
            ],
        ),
    ]
