# Generated by Django 4.1.7 on 2023-02-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leaf_types',
            new_name='Leaf_type',
        ),
    ]
