# Generated by Django 4.1.7 on 2023-02-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_rename_leaf_types_leaf_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaf',
            name='name',
            field=models.CharField(max_length=63),
        ),
    ]
