# Generated by Django 4.1.7 on 2023-02-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_alter_leaf_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Key_point',
            new_name='Keypoint',
        ),
    ]
