# Generated by Django 4.1.7 on 2023-02-20 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_rename_key_point_keypoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_leaf', to='tree.leaf')),
                ('parent_leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_leaf', to='tree.leaf')),
            ],
        ),
        migrations.AddField(
            model_name='leaf',
            name='connections',
            field=models.ManyToManyField(through='tree.Edge', to='tree.leaf'),
        ),
    ]
