# Generated by Django 4.1.7 on 2023-02-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0005_edge_leaf_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaf',
            name='object_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
