# Generated by Django 4.1.7 on 2023-02-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0006_leaf_object_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leaf_type',
            new_name='LeafType',
        ),
    ]
