# Generated by Django 4.1.7 on 2023-02-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0007_rename_leaf_type_leaftype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaf',
            name='object_count',
            field=models.IntegerField(default=26, editable=False),
        ),
    ]
