# Generated by Django 4.1.7 on 2023-02-20 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0009_alter_leaf_object_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaf',
            name='object_count',
        ),
    ]
