# Generated by Django 4.1.7 on 2023-02-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0010_remove_leaf_object_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaf',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
