# Generated by Django 4.1.7 on 2023-02-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0013_leaf_description_alter_leaf_author_alter_leaf_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaftype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
