# Generated by Django 4.1.7 on 2023-02-20 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tree', '0010_remove_leaf_object_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLeafStatus',
            fields=[
                ('id', models.IntegerField(primary_key=b'I01\n', serialize=False)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLeaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.leaf')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.studentleafstatus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.student')),
            ],
        ),
    ]
